---
title: "Assigment - Data Driven Business"
author: Xinyue Liu
date: "`r format(Sys.time(), '%d %B, %Y')`"
self_contained： false 
output:
  html_notebook:
    toc: yes
    toc_depth: 2
---

Search Youtube for suitable business case examples on data driven business. Copy the embed code below.

<<iframe width="560" height="315" src="https://www.youtube.com/embed/oQcxU1ITayI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen data—external="1"></iframe>>

## What features define a data driven business?

Companies realize that they rely more on data, rather than find new opportunities or inspirations. 

## What are the important features of a data culture?

The companies need to see their data as a strategic asset, and change the way they approach to manage data by starting an open information architecture. With the new approach, employees are freed up from the inhibitor to get to that culture. The companies  required one single version of truth, people can achieve many other new insights by infusing this one. 

## What are the transformation steps towards a mature data driven business?

Currently we are at the transitioning moment, many data resources still need to be digged out. When people really focus on implementing the analytics and machine learning, then people are able to work towards artificial intelligence, which is the a mature data driven business situation. So that the company can better serve their customers and make better decisions. 

